<?= $this->doctype() ?>
<HTML xmlns="http://www.w3.org/1999/xhtml">
<HEAD>
<TITLE>用户登录</TITLE>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headStyle(); ?>

    <LINK href="<?=$this->Url()?>/skin/login/images/Default.css" type=text/css rel=stylesheet>
    <LINK href="<?=$this->Url()?>/skin/login/images/xtree.css" type=text/css rel=stylesheet>
    <LINK href="<?=$this->Url()?>/skin/login/images/User_Login.css" type=text/css rel=stylesheet>
</HEAD>
<BODY id=userlogin_body>
<DIV></DIV>

<form action="#" method="post" />
<DIV id=user_login>
      

  <DL>
    <DD id=user_top>
      <UL>
        <LI class=user_top_l></LI>
        <LI class=user_top_c></LI>
        <LI class=user_top_r></LI>
      </UL>
    <DD id=user_main>
      <UL>
        <LI class=user_main_l></LI>
        <LI class=user_main_c>
          <DIV class=user_main_box>
            <UL>
              <LI class=user_main_text>金荣卡号： </LI>
              <LI class=user_main_input>
                <input class=TxtUserNameCssClass id=TxtUserName maxlength=20 name=username>
              </LI>
            </UL>
            <UL>
              <LI class=user_main_text>密 码： </LI>
              <LI class=user_main_input>
                <INPUT class=TxtPasswordCssClass id=TxtPassword type=password name=password>
              </LI>
            </UL>
            <UL>
              <LI class=user_main_text></LI>
              <LI class=user_main_input>
                <span style="color:red"><?php echo $this->error;?></span>
              </LI>
            </UL>
          </DIV>
        </LI>
        <LI class=user_main_r>
          <INPUT class=IbtnEnterCssClass id=IbtnEnter 
    style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" 
    type=image src="<?=$this->Url()?>/skin/login/images/user_botton.gif" name=IbtnEnter>
        </LI>
      </UL>
    <DD id=user_bottom>
     </DD>
  </DL>
</DIV>
<SPAN id=ValrUserName 
style="DISPLAY: none; COLOR: red"></SPAN><SPAN id=ValrPassword 
style="DISPLAY: none; COLOR: red"></SPAN><SPAN id=ValrValidateCode 
style="DISPLAY: none; COLOR: red"></SPAN>
<DIV id=ValidationSummary1 style="DISPLAY: none; COLOR: red"></DIV>
<DIV></DIV>
</FORM>
</BODY>
</HTML>

