<?=$this->location?>
<div class="clearfix">
	<div class="shoufukuan">
		<p class="img">
			<img src="/skin/images/fukuanren.png" id="payimg"/>&nbsp;&nbsp;付款人
		</p>
		<p>
			<span>卡号：</span><input type="text" class="transfer_input" id="paycard"/>
		</p>
		<p>
			姓名：<input type="text" class="transfer_input" id="payname" readonly="readonly"/>
		</p>
		<p>
			余额：<input type="text" class="transfer_input" id="paymoney" readonly="readonly" value="0.00"/>
		</p>
	</div>
	<div class="shoufukuanmm">
		
	</div>

	<div class="shoufukuan">
		<p class="img">
			<img src="/skin/images/shoukuanren.png" id="receiveimg"/>&nbsp;&nbsp;收款人
		</p>
		<p>
			卡号：<input type="text" class="transfer_input" id="receivecard" />
		</p>
		<p>
			姓名：<input type="text" class="transfer_input" id="receivename" readonly="readonly"/>
		</p>
	</div>
</div>
<div class="clear_fix"></div>
<br />
<!--<div class="fkje">
				<p>付款金额:</p>
				<p><input type="text" class="form-control"/></p>
				<button type="button" class="btn btn-success btn-lg">确认支付</button>
			</div>-->
<table width="430" class="zzmoney">
	<tr height="50">
		<td align="right" >
			<p style="font-size: 20px;">付款：</p>
		</td>
		<td><input type="text" class="transfer_input money" id="amount" value="0.00"/>
			<input type="hidden" id="money" value="0"/></td>
			<input type="hidden" id="paynoid" value="0"/></td>
			<input type="hidden" id="receivenoid" value="0"/></td>
	
	
	<tr>
	
	<tr height="50">
		<td></td>
		<td>
			<button type="button" class="btn btn-success btn-lg" id="btnpay">确认支付</button>
			<button type="button" style="margin-left:20px;" class="btn btn-failed" id="btnprint">重打印</button>
			<input type="hidden" id="okprint" value="0"/></td>
		</td>
	
	
	<tr>

</table>
<div class="clear_fix"></div>
<br />
<hr />
<p>说明：--------------------------------</p>
<script type="text/javascript">


// xxhtml = window.document.body.innerHTML;

// alert("xxx");
// alert(QLineEdit);
// alert("uu");
// QByte = QLineEdit.text().toLocal8Bit().fromRawData(chars,xxhtml.length);
// alert("xxx");
// QDocument.setHtml(QString.append(QByte));
// alert("xxx");
// QDocument.print(QPrinter)
//验证并加载付款后收款卡号信息

$('#paycard').focus();
$('#paycard').focus(function(){
	$(this).attr('value','');
	$('#payname').attr('value','');
	$('#payimg').attr('src','/skin/images/fukuanren.png');
	
});


$('.btn-print').live('click',function(){
	QLineEdit.show();
});
$('#receivecard').focus(function(){
	$(this).attr('value','');
	$('#receivename').attr('value','');
	$('#receiveimg').attr('src','/skin/images/shoukuanren.png');
});

$('#paycard').keypress(function(e) {
	    // 回车键事件  
	if(e.which == 13) {
		//关闭重打印按钮
		$('#btnprint').removeClass("btn-success");
		$('#btnprint').addClass("btn-failed");
		$('#btnprint').removeClass("btn-print");
		$('#btnprint').removeClass("btn-lg");

		$('#okprint').attr('value','0');
		
		cardid = $(this).attr('value');
		if (!isNaN(cardid)) {
			//判断卡是否可用，如果可用，返回卡的姓名和头像
			result = checkCard(cardid);
			if(result.stat){
				//加载图片和姓名
				$('#payname').attr({'value':result['membername']});
				$('#payimg').attr({'src':result['useimg_path']});
				$('#paymoney').attr({'value':result['amount']});
				$('#paynoid').attr({'value':result['noid']});
				//收款人获得焦点
				$('#receivecard').focus();
			}else{
				jinggao('卡号不可用或不存在');
				$this = $(this);
				$(".jinggaobtn").click(function(){
					$(".jinggaoout").remove();
					$this.focus();
					$this.attr('value','');
				});
			}
		}else{
	
			$('#payname').attr({'value':''});
		}
	}
});
$('#receivecard').keypress(function(e) {  
    // 回车键事件  
    
	if(e.which == 13) {
		cardid = $(this).attr('value');
		if (!isNaN(cardid)) {
			//判断是否同一张卡
			if (cardid == $('#paycard').attr('value')) {				
				
				jinggao('同一张卡不可转账');
				$this = $(this);
				$(".jinggaobtn").click(function(){
					$(".jinggaoout").remove();			
					$this.focus();
					return;
				});
			}
			//判断卡是否可用，如果可用，返回卡的姓名和头像
			result = checkCard(cardid);
			if(result.stat){
				//收款人获得焦点
				$('#receivename').attr({'value':result['membername']});
				$('#receiveimg').attr({'src':result['useimg_path']});
				$('#receivenoid').attr({'value':result['noid']});
				showKeyboardMoney();
			}else{
			
				jinggao('卡号不可用或不存在');
				$this = $(this);
				$(".jinggaobtn").click(function(){
					$(".jinggaoout").remove();			
					$this.focus();
					$this.attr('value','');
				});
			}
		}else{
	
			$('#receivename').attr({'value':''});
		}
	}
});

$('input.transfer_input[readonly=readonly]').css({'background':'#ddd'});

$('#amount').focus(function(){

	showKeyboardMoney();
});

//点击支付
$('#btnpay').click(function(){

	//验证付款字段输入是否合法
	if(payLegal()){

		//验证用户名卡号是否正确
		if (isrealCard($('#paycard').attr('value')) && 
			isrealCard($('#receivecard').attr('value'))
			) {
			//输入密码
			if ($('#paycard').attr('value') == $('#receivecard').attr('value')) {

				jinggao("同一张卡不可转账");
				$this = $(this);
				$(".jinggaobtn").click(function(){
					$(".jinggaoout").remove();	
					$('#receivecard').focus();
					return ;		
					});
			}
			showKeyboard();
		}else{
			jinggao('卡号或姓名错误，请修改');
			$(".jinggaobtn").click(function(){
				$(".jinggaoout").remove();			
			});
		}
	}
});

//验证密码
	
</script>


