<?=$this->location?>

<div class="mj_list">
	<div class="table_title clearfix">
			<div class="title_left"><?=$this->module?></div>
			<div class="jrsc_fy" >
				<ul class="pagination">
					<?php 
						if ($this->PageList['left']) {?>
					<li><a href="<?=$this->url?>/stock/mystock?pageNum=1">&laquo;</a></li>
						<?php }
						if ($this->PageList['leftdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						foreach ($this->PageList['list'] as $v){
							$class=($v == $this->currentPage)?"class='active'":"";
					?>
					<li <?=$class?>><a href="<?=$this->url?>/stock/mystock?pageNum=<?=$v?>"><?=$v?></a></li>
						<?php }
					if ($this->PageList['rightdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						if ($this->PageList['right']) {?>
					<li><a href="<?=$this->url?>/stock/mystock?pageNum=<?=$this->totalPage?>">&raquo;</a></li>
						<?php }
					?>
				</ul>
			</div>
		</div> 
		<div class="rk_table">
			<table class="data_table" border="0" cellpadding="0" cellspacing="0">
				<thead>
				<tr>
					<th ><span style="background-color: #17d2fa;"></span>商品编号</th>
					<th ><span style="background-color: #17fa61;"></span>商品名称</th>
					<th ><span style="background-color: #e9bb2e;"></span>库存量</th>
					<th ><span style="background-color: #be08ce;"></span>计量单位</th>
				</tr>
				</thead>
				<tbody>
			<?php 
				foreach ($this->list as $k=>$v){?>
					
				<tr>
					<td><?=$v['goods_id']?></td>
					<td><?=$v['pname']?></td>
					<td><?=floor($v['goods_numbers'])?></td>
					<td><?=$v['unit']?></td>
				</tr>
				<?php }
			?>
				</tbody>
			</table>

		</div>
		<hr />
				
	<?php
	
		$classleft = ($this->currentPage == 1)?"slidehide":"";
		$classright = ($this->currentPage == $this->totalPage)?"slidehide":"";
		if($this->totalPage <=1){
			$classleft='slidehide';
			$classright='slidehide';
		}
	?>
	<div class="slide slideleft <?=$classleft?>"><a href="<?=$this->url?>/stock/mystock?pageNum=<?=($this->currentPage-1)?>">&nbsp;</a></div>
	<div class="slide slideright <?=$classright?>"><a href="<?=$this->url?>/stock/mystock?pageNum=<?=($this->currentPage+1)?>">&nbsp;</a></div>		
		
</div>
<script>
	
	$('.query').click(function(){
		
		});

	$('#load_data a').click(function(){

		rightATagClickListener($(this),'');
		return false;
		});


	//隔行变色
	$(".data_table tbody tr:odd td").css("background","#cbefde");
		
	//翻页
	slidesome();
</script>