# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/maintab.ui'
#
# Created: Sun Mar 08 11:02:03 2015
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(894, 540)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.widget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.widget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.widget_2 = QtGui.QWidget(Dialog)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_3 = QtGui.QWidget(self.widget_2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_6 = QtGui.QPushButton(self.widget_3)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.widget_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.widget_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.widget_2)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.widget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_5 = QtGui.QWidget(self.widget_2)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_10 = QtGui.QLabel(self.widget_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget_6 = QtGui.QWidget(self.widget_2)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.pushButton_12 = QtGui.QPushButton(self.widget_6)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.verticalLayout_7.addWidget(self.pushButton_12)
        self.pushButton_13 = QtGui.QPushButton(self.widget_6)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.verticalLayout_7.addWidget(self.pushButton_13)
        self.horizontalLayout.addWidget(self.widget_6)
        self.widget_7 = QtGui.QWidget(self.widget_2)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_7)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_11 = QtGui.QLabel(self.widget_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout.addWidget(self.widget_7)
        self.widget_8 = QtGui.QWidget(self.widget_2)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_8)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_13 = QtGui.QLabel(self.widget_8)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_9.addWidget(self.label_13)
        self.horizontalLayout.addWidget(self.widget_8)
        self.widget_9 = QtGui.QWidget(self.widget_2)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_9)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.pushButton_14 = QtGui.QPushButton(self.widget_9)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.verticalLayout_10.addWidget(self.pushButton_14)
        self.pushButton_15 = QtGui.QPushButton(self.widget_9)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.verticalLayout_10.addWidget(self.pushButton_15)
        self.horizontalLayout.addWidget(self.widget_9)
        self.widget_10 = QtGui.QWidget(self.widget_2)
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.widget_10)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_18 = QtGui.QLabel(self.widget_10)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_18.addWidget(self.label_18)
        self.horizontalLayout.addWidget(self.widget_10)
        self.widget_18 = QtGui.QWidget(self.widget_2)
        self.widget_18.setObjectName(_fromUtf8("widget_18"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.widget_18)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_19 = QtGui.QLabel(self.widget_18)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.horizontalLayout.addWidget(self.widget_18)
        self.widget_19 = QtGui.QWidget(self.widget_2)
        self.widget_19.setObjectName(_fromUtf8("widget_19"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.widget_19)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.pushButton_23 = QtGui.QPushButton(self.widget_19)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.verticalLayout_20.addWidget(self.pushButton_23)
        self.horizontalLayout.addWidget(self.widget_19)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton.setText(_translate("Dialog", "PushButton", None))
        self.label.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_2.setText(_translate("Dialog", "PushButton", None))
        self.label_2.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_3.setText(_translate("Dialog", "PushButton", None))
        self.label_4.setText(_translate("Dialog", "TextLabel", None))
        self.label_5.setText(_translate("Dialog", "TextLabel", None))
        self.label_3.setText(_translate("Dialog", "TextLabel", None))
        self.label_6.setText(_translate("Dialog", "TextLabel", None))
        self.label_7.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_4.setText(_translate("Dialog", "PushButton", None))
        self.pushButton_5.setText(_translate("Dialog", "PushButton", None))
        self.label_8.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_6.setText(_translate("Dialog", "PushButton", None))
        self.pushButton_7.setText(_translate("Dialog", "PushButton", None))
        self.pushButton_8.setText(_translate("Dialog", "PushButton", None))
        self.label_9.setText(_translate("Dialog", "TextLabel", None))
        self.label_10.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_12.setText(_translate("Dialog", "PushButton", None))
        self.pushButton_13.setText(_translate("Dialog", "PushButton", None))
        self.label_11.setText(_translate("Dialog", "TextLabel", None))
        self.label_13.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_14.setText(_translate("Dialog", "PushButton", None))
        self.pushButton_15.setText(_translate("Dialog", "PushButton", None))
        self.label_18.setText(_translate("Dialog", "TextLabel", None))
        self.label_19.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_23.setText(_translate("Dialog", "PushButton", None))

