# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderDetail.ui'
#
# Created: Thu Oct 30 10:51:15 2014
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1010, 695)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_5 = QtGui.QWidget(self.groupBox)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(self.widget_5)
        self.label.setMinimumSize(QtCore.QSize(60, 25))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.widget_5)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(120, 25))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.label_2 = QtGui.QLabel(self.widget_5)
        self.label_2.setMinimumSize(QtCore.QSize(60, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_3 = QtGui.QComboBox(self.widget_5)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_6.addWidget(self.comboBox_3)
        self.label_3 = QtGui.QLabel(self.widget_5)
        self.label_3.setMinimumSize(QtCore.QSize(60, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.comboBox = QtGui.QComboBox(self.widget_5)
        self.comboBox.setEnabled(False)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.label_7 = QtGui.QLabel(self.widget_5)
        self.label_7.setMinimumSize(QtCore.QSize(100, 25))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.comboBox_2 = QtGui.QComboBox(self.widget_5)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.label_10 = QtGui.QLabel(self.widget_5)
        self.label_10.setMinimumSize(QtCore.QSize(90, 25))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        self.dateEdit_2 = QtGui.QDateEdit(self.widget_5)
        self.dateEdit_2.setEnabled(False)
        self.dateEdit_2.setMinimumSize(QtCore.QSize(100, 25))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.horizontalLayout_6.addWidget(self.dateEdit_2)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtGui.QWidget(self.groupBox)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_12 = QtGui.QLabel(self.widget_6)
        self.label_12.setMinimumSize(QtCore.QSize(60, 25))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.lineEdit_6 = QtGui.QLineEdit(self.widget_6)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(120, 25))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.label_11 = QtGui.QLabel(self.widget_6)
        self.label_11.setMinimumSize(QtCore.QSize(60, 25))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.comboBox_4 = QtGui.QComboBox(self.widget_6)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout_7.addWidget(self.comboBox_4)
        self.label_5 = QtGui.QLabel(self.widget_6)
        self.label_5.setMinimumSize(QtCore.QSize(60, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.comboBox_5 = QtGui.QComboBox(self.widget_6)
        self.comboBox_5.setEnabled(False)
        self.comboBox_5.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBox_5)
        self.label_6 = QtGui.QLabel(self.widget_6)
        self.label_6.setMinimumSize(QtCore.QSize(100, 25))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.comboBox_6 = QtGui.QComboBox(self.widget_6)
        self.comboBox_6.setEnabled(False)
        self.comboBox_6.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBox_6)
        self.label_9 = QtGui.QLabel(self.widget_6)
        self.label_9.setMinimumSize(QtCore.QSize(90, 25))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.dateEdit = QtGui.QDateEdit(self.widget_6)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 25))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_7.addWidget(self.dateEdit)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(50, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(160, 30))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "订单详情", None))
        self.groupBox.setTitle(_translate("Dialog", "订单详情", None))
        self.label.setText(_translate("Dialog", "订 单 号 ：", None))
        self.label_2.setText(_translate("Dialog", "采 购 员 ：", None))
        self.label_3.setText(_translate("Dialog", "订单状态 ：", None))
        self.comboBox.setItemText(0, _translate("Dialog", "关闭", None))
        self.comboBox.setItemText(1, _translate("Dialog", "未入库", None))
        self.comboBox.setItemText(2, _translate("Dialog", "已入库", None))
        self.comboBox.setItemText(3, _translate("Dialog", "发货中", None))
        self.comboBox.setItemText(4, _translate("Dialog", "完成", None))
        self.label_7.setText(_translate("Dialog", "竞  价  方 式 ：", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "指派供应商", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "供应商竞价", None))
        self.label_10.setText(_translate("Dialog", "预 计 完 成 ：", None))
        self.label_12.setText(_translate("Dialog", "佣    金 ：", None))
        self.label_11.setText(_translate("Dialog", "供 应 商 ：", None))
        self.label_5.setText(_translate("Dialog", "已付货款 ：", None))
        self.comboBox_5.setItemText(0, _translate("Dialog", "否", None))
        self.comboBox_5.setItemText(1, _translate("Dialog", "是", None))
        self.label_6.setText(_translate("Dialog", "供应商接受订单：", None))
        self.comboBox_6.setItemText(0, _translate("Dialog", "否", None))
        self.comboBox_6.setItemText(1, _translate("Dialog", "是", None))
        self.label_9.setText(_translate("Dialog", "创 建 日 期 ：", None))
        self.groupBox_2.setTitle(_translate("Dialog", "商品清单", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "条形码", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "商品名称", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "单价", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "采购数量", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "单位", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "总价", None))
        self.label_4.setText(_translate("Dialog", " 订单总额：", None))
        self.pushButton.setText(_translate("Dialog", "修 改 订 单", None))

