# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quxian.ui'
#
# Created: Mon May 25 16:32:11 2015
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1000, 522)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(1000, 580))
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(380, 210))
        self.groupBox_4.setMaximumSize(QtCore.QSize(380, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4.addWidget(self.groupBox_4, 1, 2, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setMinimumSize(QtCore.QSize(60, 30))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.bankusername = QtGui.QLineEdit(self.groupBox_2)
        self.bankusername.setEnabled(True)
        self.bankusername.setMinimumSize(QtCore.QSize(0, 30))
        self.bankusername.setReadOnly(True)
        self.bankusername.setObjectName(_fromUtf8("bankusername"))
        self.gridLayout_2.addWidget(self.bankusername, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setMinimumSize(QtCore.QSize(60, 30))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.bankname = QtGui.QLineEdit(self.groupBox_2)
        self.bankname.setEnabled(True)
        self.bankname.setMinimumSize(QtCore.QSize(0, 30))
        self.bankname.setReadOnly(True)
        self.bankname.setObjectName(_fromUtf8("bankname"))
        self.gridLayout_2.addWidget(self.bankname, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setMinimumSize(QtCore.QSize(60, 30))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.bankcard = QtGui.QLineEdit(self.groupBox_2)
        self.bankcard.setEnabled(True)
        self.bankcard.setMinimumSize(QtCore.QSize(0, 30))
        self.bankcard.setReadOnly(True)
        self.bankcard.setObjectName(_fromUtf8("bankcard"))
        self.gridLayout_2.addWidget(self.bankcard, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setMinimumSize(QtCore.QSize(60, 30))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 2, 1, 1)
        self.bankadder = QtGui.QLineEdit(self.groupBox_2)
        self.bankadder.setEnabled(True)
        self.bankadder.setMinimumSize(QtCore.QSize(0, 30))
        self.bankadder.setReadOnly(True)
        self.bankadder.setObjectName(_fromUtf8("bankadder"))
        self.gridLayout_2.addWidget(self.bankadder, 1, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 3, 0, 1, 5)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(60, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.membername = QtGui.QLineEdit(self.groupBox)
        self.membername.setEnabled(True)
        self.membername.setMinimumSize(QtCore.QSize(0, 30))
        self.membername.setReadOnly(True)
        self.membername.setObjectName(_fromUtf8("membername"))
        self.gridLayout.addWidget(self.membername, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(60, 30))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 3, 1, 1)
        self.cardid = QtGui.QLineEdit(self.groupBox)
        self.cardid.setEnabled(True)
        self.cardid.setMinimumSize(QtCore.QSize(0, 30))
        self.cardid.setReadOnly(True)
        self.cardid.setObjectName(_fromUtf8("cardid"))
        self.gridLayout.addWidget(self.cardid, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(60, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.sex = QtGui.QComboBox(self.groupBox)
        self.sex.setEnabled(True)
        self.sex.setMinimumSize(QtCore.QSize(0, 30))
        self.sex.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sex.setEditable(True)
        self.sex.setDuplicatesEnabled(False)
        self.sex.setObjectName(_fromUtf8("sex"))
        self.sex.addItem(_fromUtf8(""))
        self.sex.addItem(_fromUtf8(""))
        self.sex.addItem(_fromUtf8(""))
        self.sex.setItemText(2, _fromUtf8(""))
        self.gridLayout.addWidget(self.sex, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(60, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.tel = QtGui.QLineEdit(self.groupBox)
        self.tel.setEnabled(True)
        self.tel.setMinimumSize(QtCore.QSize(0, 30))
        self.tel.setReadOnly(True)
        self.tel.setObjectName(_fromUtf8("tel"))
        self.gridLayout.addWidget(self.tel, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(60, 30))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.nation = QtGui.QLineEdit(self.groupBox)
        self.nation.setEnabled(True)
        self.nation.setMinimumSize(QtCore.QSize(0, 30))
        self.nation.setReadOnly(True)
        self.nation.setObjectName(_fromUtf8("nation"))
        self.gridLayout.addWidget(self.nation, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(60, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.idcard = QtGui.QLineEdit(self.groupBox)
        self.idcard.setEnabled(True)
        self.idcard.setMinimumSize(QtCore.QSize(0, 30))
        self.idcard.setReadOnly(True)
        self.idcard.setObjectName(_fromUtf8("idcard"))
        self.gridLayout.addWidget(self.idcard, 2, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setMinimumSize(QtCore.QSize(60, 30))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setMinimumSize(QtCore.QSize(60, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.adder = QtGui.QLineEdit(self.groupBox)
        self.adder.setEnabled(True)
        self.adder.setMinimumSize(QtCore.QSize(0, 30))
        self.adder.setReadOnly(True)
        self.adder.setObjectName(_fromUtf8("adder"))
        self.gridLayout.addWidget(self.adder, 3, 4, 1, 1)
        self.carddate = QtGui.QLineEdit(self.groupBox)
        self.carddate.setEnabled(True)
        self.carddate.setMinimumSize(QtCore.QSize(0, 30))
        self.carddate.setReadOnly(True)
        self.carddate.setObjectName(_fromUtf8("carddate"))
        self.gridLayout.addWidget(self.carddate, 3, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 5)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(230, 210))
        self.groupBox_3.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget = QtGui.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(20, 22, 191, 170))
        self.widget.setMinimumSize(QtCore.QSize(190, 170))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.records_txt_3 = QtGui.QTextEdit(self.groupBox_5)
        self.records_txt_3.setEnabled(True)
        self.records_txt_3.setObjectName(_fromUtf8("records_txt_3"))
        self.gridLayout_3.addWidget(self.records_txt_3, 2, 0, 1, 1)
        self.records_txt = QtGui.QTextEdit(self.groupBox_5)
        self.records_txt.setEnabled(True)
        self.records_txt.setObjectName(_fromUtf8("records_txt"))
        self.gridLayout_3.addWidget(self.records_txt, 0, 0, 1, 1)
        self.records_txt_2 = QtGui.QTextEdit(self.groupBox_5)
        self.records_txt_2.setEnabled(True)
        self.records_txt_2.setObjectName(_fromUtf8("records_txt_2"))
        self.gridLayout_3.addWidget(self.records_txt_2, 1, 0, 1, 1)
        self.records_txt_4 = QtGui.QTextEdit(self.groupBox_5)
        self.records_txt_4.setEnabled(True)
        self.records_txt_4.setObjectName(_fromUtf8("records_txt_4"))
        self.gridLayout_3.addWidget(self.records_txt_4, 3, 0, 1, 1)
        self.webView = QtWebKit.QWebView(self.groupBox_5)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("file:///E:/www/kmvip/src/print/model.html")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayout_3.addWidget(self.webView, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 6, 3, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(Dialog)
        self.commandLinkButton_2.setEnabled(False)
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.gridLayout_4.addWidget(self.commandLinkButton_2, 0, 4, 1, 1)
        self.commandLinkButton_3 = QtGui.QCommandLinkButton(Dialog)
        self.commandLinkButton_3.setEnabled(True)
        self.commandLinkButton_3.setObjectName(_fromUtf8("commandLinkButton_3"))
        self.gridLayout_4.addWidget(self.commandLinkButton_3, 0, 6, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.inputcardid = QtGui.QLineEdit(Dialog)
        self.inputcardid.setMinimumSize(QtCore.QSize(0, 30))
        self.inputcardid.setObjectName(_fromUtf8("inputcardid"))
        self.gridLayout_4.addWidget(self.inputcardid, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.sex.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.inputcardid, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.commandLinkButton_3)
        Dialog.setTabOrder(self.commandLinkButton_3, self.commandLinkButton_2)
        Dialog.setTabOrder(self.commandLinkButton_2, self.membername)
        Dialog.setTabOrder(self.membername, self.bankusername)
        Dialog.setTabOrder(self.bankusername, self.bankname)
        Dialog.setTabOrder(self.bankname, self.bankcard)
        Dialog.setTabOrder(self.bankcard, self.bankadder)
        Dialog.setTabOrder(self.bankadder, self.cardid)
        Dialog.setTabOrder(self.cardid, self.sex)
        Dialog.setTabOrder(self.sex, self.tel)
        Dialog.setTabOrder(self.tel, self.nation)
        Dialog.setTabOrder(self.nation, self.idcard)
        Dialog.setTabOrder(self.idcard, self.adder)
        Dialog.setTabOrder(self.adder, self.carddate)
        Dialog.setTabOrder(self.carddate, self.records_txt_3)
        Dialog.setTabOrder(self.records_txt_3, self.records_txt)
        Dialog.setTabOrder(self.records_txt, self.records_txt_2)
        Dialog.setTabOrder(self.records_txt_2, self.records_txt_4)
        Dialog.setTabOrder(self.records_txt_4, self.webView)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "取现", None))
        self.groupBox_4.setTitle(_translate("Dialog", "身份证扫描件", None))
        self.groupBox_2.setTitle(_translate("Dialog", "银行信息", None))
        self.label_10.setText(_translate("Dialog", "开 户 名：", None))
        self.label_11.setText(_translate("Dialog", "开 户 行：", None))
        self.label_12.setText(_translate("Dialog", "开户账号：", None))
        self.label_13.setText(_translate("Dialog", "开 户 点：", None))
        self.groupBox.setTitle(_translate("Dialog", "基本资料", None))
        self.label_2.setText(_translate("Dialog", "客户姓名：", None))
        self.label_14.setText(_translate("Dialog", "会员卡号：", None))
        self.label_3.setText(_translate("Dialog", "性    别：", None))
        self.sex.setItemText(0, _translate("Dialog", "女", None))
        self.sex.setItemText(1, _translate("Dialog", "男", None))
        self.label_5.setText(_translate("Dialog", "联系电话：", None))
        self.label_6.setText(_translate("Dialog", "民    族：", None))
        self.label_7.setText(_translate("Dialog", "身 份 证：", None))
        self.label_9.setText(_translate("Dialog", "有 效 期：", None))
        self.label_8.setText(_translate("Dialog", "联系地址：", None))
        self.groupBox_3.setTitle(_translate("Dialog", "照片", None))
        self.groupBox_5.setTitle(_translate("Dialog", "近期交易明细", None))
        self.records_txt_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.records_txt.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.records_txt_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.records_txt_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_4.setText(_translate("Dialog", "可用余额：", None))
        self.commandLinkButton_2.setText(_translate("Dialog", "提现下一步", None))
        self.commandLinkButton_3.setText(_translate("Dialog", "重打印", None))
        self.label.setText(_translate("Dialog", "会员卡号：", None))

from PyQt4 import QtWebKit
