# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'useradd.ui'
#
# Created: Tue May 26 10:45:02 2015
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(563, 720)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.username = QtGui.QLineEdit(self.widget)
        self.username.setMinimumSize(QtCore.QSize(0, 0))
        self.username.setMaximumSize(QtCore.QSize(16777215, 30))
        self.username.setText(_fromUtf8(""))
        self.username.setObjectName(_fromUtf8("username"))
        self.horizontalLayout.addWidget(self.username)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.group = QtGui.QComboBox(self.widget)
        self.group.setMaximumSize(QtCore.QSize(110, 30))
        self.group.setObjectName(_fromUtf8("group"))
        self.horizontalLayout.addWidget(self.group)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(Dialog)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.nickname = QtGui.QLineEdit(self.widget_2)
        self.nickname.setMinimumSize(QtCore.QSize(0, 0))
        self.nickname.setMaximumSize(QtCore.QSize(16777215, 30))
        self.nickname.setText(_fromUtf8(""))
        self.nickname.setObjectName(_fromUtf8("nickname"))
        self.horizontalLayout_2.addWidget(self.nickname)
        self.label_7 = QtGui.QLabel(self.widget_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.hukou = QtGui.QLineEdit(self.widget_2)
        self.hukou.setMinimumSize(QtCore.QSize(0, 0))
        self.hukou.setMaximumSize(QtCore.QSize(16777215, 30))
        self.hukou.setObjectName(_fromUtf8("hukou"))
        self.horizontalLayout_2.addWidget(self.hukou)
        self.label_11 = QtGui.QLabel(self.widget_2)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.sex = QtGui.QComboBox(self.widget_2)
        self.sex.setMaximumSize(QtCore.QSize(110, 30))
        self.sex.setObjectName(_fromUtf8("sex"))
        self.sex.addItem(_fromUtf8(""))
        self.sex.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.sex)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_6 = QtGui.QWidget(Dialog)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_13 = QtGui.QLabel(self.widget_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.tel = QtGui.QLineEdit(self.widget_6)
        self.tel.setMinimumSize(QtCore.QSize(0, 0))
        self.tel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tel.setText(_fromUtf8(""))
        self.tel.setObjectName(_fromUtf8("tel"))
        self.horizontalLayout_6.addWidget(self.tel)
        self.label_6 = QtGui.QLabel(self.widget_6)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.birthday = QtGui.QDateEdit(self.widget_6)
        self.birthday.setMinimumSize(QtCore.QSize(0, 30))
        self.birthday.setAccelerated(False)
        self.birthday.setCalendarPopup(True)
        self.birthday.setObjectName(_fromUtf8("birthday"))
        self.horizontalLayout_6.addWidget(self.birthday)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_7 = QtGui.QWidget(Dialog)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.widget_7)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.card = QtGui.QLineEdit(self.widget_7)
        self.card.setMinimumSize(QtCore.QSize(0, 0))
        self.card.setMaximumSize(QtCore.QSize(16777215, 30))
        self.card.setText(_fromUtf8(""))
        self.card.setObjectName(_fromUtf8("card"))
        self.horizontalLayout_7.addWidget(self.card)
        self.label_3 = QtGui.QLabel(self.widget_7)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.comboBox = QtGui.QComboBox(self.widget_7)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_9 = QtGui.QWidget(Dialog)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_16 = QtGui.QLabel(self.widget_9)
        self.label_16.setMinimumSize(QtCore.QSize(0, 30))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_9.addWidget(self.label_16)
        self.password = QtGui.QLineEdit(self.widget_9)
        self.password.setMinimumSize(QtCore.QSize(0, 0))
        self.password.setMaximumSize(QtCore.QSize(16777215, 30))
        self.password.setText(_fromUtf8(""))
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_9.addWidget(self.password)
        self.label_15 = QtGui.QLabel(self.widget_9)
        self.label_15.setMinimumSize(QtCore.QSize(0, 30))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.password2 = QtGui.QLineEdit(self.widget_9)
        self.password2.setMinimumSize(QtCore.QSize(0, 0))
        self.password2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.password2.setText(_fromUtf8(""))
        self.password2.setEchoMode(QtGui.QLineEdit.Password)
        self.password2.setObjectName(_fromUtf8("password2"))
        self.horizontalLayout_9.addWidget(self.password2)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_11 = QtGui.QWidget(Dialog)
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.widget_11)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.adder = QtGui.QLineEdit(self.widget_11)
        self.adder.setMinimumSize(QtCore.QSize(0, 0))
        self.adder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.adder.setObjectName(_fromUtf8("adder"))
        self.horizontalLayout_11.addWidget(self.adder)
        self.verticalLayout_2.addWidget(self.widget_11)
        self.widget_14 = QtGui.QWidget(Dialog)
        self.widget_14.setObjectName(_fromUtf8("widget_14"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.widget_14)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox = QtGui.QGroupBox(self.widget_14)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_4 = QtGui.QWidget(self.groupBox)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 170))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_5.addWidget(self.widget_4)
        self.horizontalLayout_13.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.widget_14)
        self.widget_13 = QtGui.QWidget(Dialog)
        self.widget_13.setObjectName(_fromUtf8("widget_13"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_13)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setMargin(3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.tabWidget = QtGui.QTabWidget(self.widget_13)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.shenfenzhengimage = QtGui.QWidget(self.tab)
        self.shenfenzhengimage.setObjectName(_fromUtf8("shenfenzhengimage"))
        self.verticalLayout_3.addWidget(self.shenfenzhengimage)
        self.shenfenzheng = QtGui.QPushButton(self.tab)
        self.shenfenzheng.setMinimumSize(QtCore.QSize(0, 30))
        self.shenfenzheng.setObjectName(_fromUtf8("shenfenzheng"))
        self.verticalLayout_3.addWidget(self.shenfenzheng)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.shenfenzhengimage_t = QtGui.QWidget(self.tab_2)
        self.shenfenzhengimage_t.setObjectName(_fromUtf8("shenfenzhengimage_t"))
        self.verticalLayout_4.addWidget(self.shenfenzhengimage_t)
        self.shenfenzheng_t = QtGui.QPushButton(self.tab_2)
        self.shenfenzheng_t.setMinimumSize(QtCore.QSize(0, 30))
        self.shenfenzheng_t.setObjectName(_fromUtf8("shenfenzheng_t"))
        self.verticalLayout_4.addWidget(self.shenfenzheng_t)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.tabWidget)
        self.widget_12 = QtGui.QWidget(self.widget_13)
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_12)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_8 = QtGui.QPushButton(self.widget_12)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_6 = QtGui.QPushButton(self.widget_12)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_4 = QtGui.QPushButton(self.widget_12)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widget_12)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout_12.addWidget(self.widget_12)
        self.verticalLayout_2.addWidget(self.widget_13)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username, self.group)
        Dialog.setTabOrder(self.group, self.nickname)
        Dialog.setTabOrder(self.nickname, self.hukou)
        Dialog.setTabOrder(self.hukou, self.sex)
        Dialog.setTabOrder(self.sex, self.tel)
        Dialog.setTabOrder(self.tel, self.birthday)
        Dialog.setTabOrder(self.birthday, self.card)
        Dialog.setTabOrder(self.card, self.password)
        Dialog.setTabOrder(self.password, self.password2)
        Dialog.setTabOrder(self.password2, self.adder)
        Dialog.setTabOrder(self.adder, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.shenfenzheng)
        Dialog.setTabOrder(self.shenfenzheng, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.pushButton_6)
        Dialog.setTabOrder(self.pushButton_6, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.pushButton_5)
        Dialog.setTabOrder(self.pushButton_5, self.shenfenzheng_t)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "添加员工", None))
        self.label.setText(_translate("Dialog", "登 录 名：", None))
        self.label_14.setText(_translate("Dialog", "所 在 组：", None))
        self.label_2.setText(_translate("Dialog", "姓    名：", None))
        self.label_7.setText(_translate("Dialog", "户  籍：", None))
        self.label_11.setText(_translate("Dialog", "性  别：", None))
        self.sex.setItemText(0, _translate("Dialog", "女", None))
        self.sex.setItemText(1, _translate("Dialog", "男", None))
        self.label_13.setText(_translate("Dialog", "联系电话：", None))
        self.label_6.setText(_translate("Dialog", "生  日：", None))
        self.label_5.setText(_translate("Dialog", "身 份 证：", None))
        self.label_3.setText(_translate("Dialog", "业务授权权限：", None))
        self.comboBox.setItemText(0, _translate("Dialog", "无", None))
        self.comboBox.setItemText(1, _translate("Dialog", "有", None))
        self.label_16.setText(_translate("Dialog", "密   码：", None))
        self.label_15.setText(_translate("Dialog", "确认密码：", None))
        self.label_9.setText(_translate("Dialog", "住宅地址：", None))
        self.groupBox.setTitle(_translate("Dialog", "照片", None))
        self.shenfenzheng.setText(_translate("Dialog", "选择图像", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "身份证正面", None))
        self.shenfenzheng_t.setText(_translate("Dialog", "选择图像", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "身份证反面", None))
        self.pushButton_8.setText(_translate("Dialog", "指纹录入", None))
        self.pushButton_6.setText(_translate("Dialog", "拍照", None))
        self.pushButton_4.setText(_translate("Dialog", "添加", None))
        self.pushButton_5.setText(_translate("Dialog", "取消", None))

