<?=$this->location?>
<table class="cx_select">
	<tr>
		<td>
			<input type="button" class="btn btn-success btn-caigou" value="采购出库"/>
			<!-- 
			<input type="button" class="btn btn-success btn-zizhu" value="自主出库"/>
			 -->
		</td>
		
	</tr>
</table>

<div class="clear_fix"></div>
<div class="mj_list">
	<div class="table_title clearfix">
			<div class="title_left"><?=$this->module?></div>
			<div class="jrsc_fy" >
				<ul class="pagination">
					<?php 
						if ($this->PageList['left']) {?>
					<li><a href="<?=$this->url?>/stock/stockout?pageNum=1">&laquo;</a></li>
						<?php }
						if ($this->PageList['leftdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						foreach ($this->PageList['list'] as $v){
							$class=($v == $this->currentPage)?"class='active'":"";
					?>
					<li <?=$class?>><a href="<?=$this->url?>/stock/stockout?pageNum=<?=$v?>"><?=$v?></a></li>
						<?php }
					if ($this->PageList['rightdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						if ($this->PageList['right']) {?>
					<li><a href="<?=$this->url?>/stock/stockout?pageNum=<?=$this->totalPage?>">&raquo;</a></li>
						<?php }
					?>
				</ul>
			</div>
		</div> 
		<div class="rk_table">
			<table class="data_table" border="0" cellpadding="0" cellspacing="0">
				<thead>
				<tr>
					<th >出库类别</th>
					<th >原始单号</th>
					<th >出库单号</th>
					<th >创建时间</th>
					<th >出库时间</th>
					<th >操作</th>
				</tr>
				</thead>
				<tbody>
			<?php 
				foreach ($this->list as $k=>$v){?>
					
				<tr>
					<td><?=$v['type']?></td>
					<td><?=$v['ordersn']?></td>
					<td><?=$v['stock_on']?></td>
					<td><?=$v['cdate']?></td>
					<td><?=$v['indate']?></td>
					<td class="goto"><a href="<?=$this->url?>/stock/stockout/info?id=<?=$v['id']?>">详情</a></td>
				</tr>
				<?php }
			?>
				</tbody>
			</table>

		</div>
		<hr />
		
	<?php
	
		$classleft = ($this->currentPage == 1)?"slidehide":"";
		$classright = ($this->currentPage == $this->totalPage)?"slidehide":"";	
		if($this->totalPage <=1){
			$classleft='slidehide';
			$classright='slidehide';
		}
	?>
	<div class="slide slideleft <?=$classleft?>"><a href="<?=$this->url?>/stock/stockout?pageNum=<?=($this->currentPage-1)?>">&nbsp;</a></div>
	<div class="slide slideright <?=$classright?>"><a href="<?=$this->url?>/stock/stockout?pageNum=<?=($this->currentPage+1)?>">&nbsp;</a></div>		
		
</div>
<div class="clear_fix"></div>
<div id="selectOrderDlg">
	<span style="float:left;line-height:30px;">选择订单：</span>
	<span><select class="form-control" style="width:70%;float:left;"></select></span>
	
	<div class="clear_fix"></div>
	<div style="padding:20px 0px 5px 80px;text-align:center;">
		<input type="hidden" class="inputtype" value="-1"/>
		<input type="button" class="btn btn-success btn-into" value="确定"/>
		<input type="button" class="btn btn-failed btn-nointo" value="取消"/>
	</div>
</div>
<script>
	
	$('.query').click(function(){
		
		});
	//出库界面
	$('.btn-into').click(function(){
		//获取选择订单
// 		alert($('#selectOrderDlg select').attr('value'));

		if($('#selectOrderDlg select').attr('value') == 0 || $('#selectOrderDlg select').attr('value')<1){
			jinggao("请选择订单");
			$this = $(this);
			$(".jinggaobtn").click(function(){
				$(".jinggaoout").remove();	
			});
		}else{
			data = 'oid='+$('#selectOrderDlg select').attr('value');
			data += '&type='+$('.inputtype').attr('value');
			loadRightData('/stock/stockout/pageoutput','post',data);
		}
		
	
	});
	$('.btn-caigou').click(function(){
		$('.inputtype').attr('value',0);
		result = ajaxPost('','/stock/stockout/orderlist');
		if(result.stat){
			html = '';
 				html +='<option value ="0">请选择</option>';
			for(var i =0; i<result.data.length;i++){
 				html +='<option value ="'+result.data[i].id+'">'+result.data[i].ordersn+'</option>';
			}
			$('#selectOrderDlg select').append(html);
			$('#selectOrderDlg').show();
			
		}else{

		}
	});	
	
	$('.btn-nointo').click(function(){
		$('#selectOrderDlg').hide();
		$('#selectOrderDlg select').empty();
	});
	
	//鼠标经过
	$('.data_table tbody tr').hover(function(){
		$("td",this).css("background","#ccc");
	},function(){
		$("td",this).css("background",$(this).attr("background"));
	});
	
	
	//点击行
	$('.data_table tbody tr').click(function(){
		rightATagClickListener($("td.goto a",this),'');
	});
	
	$('#load_data a').click(function(){

		rightATagClickListener($(this),'');
		return false;
		});


	//隔行变色
	$(".data_table tbody tr:even").attr("background","#fff");
	$(".data_table tbody tr:odd").attr("background","#cbefde");
	$(".data_table tbody tr:odd td").css("background","#cbefde");
	
	//翻页
	slidesome();
	
</script>