<?=$this->location?>
<table class="cx_select">
	<tr>
		<td>出库类型：</td>
		<td class="select">
			<input type="text" value="<?=$this->inputtype?>" readonly="readonly"/>
		</td>
		<td>出库单号：</td>
		<td class="select">
			<input type="text" value="<?=$this->stock_on?>" class="stock_on" readonly="readonly"/>
		</td>
		<td>原始单号：</td>
		<td class="select">
			<input type="text" value="<?=$this->list[0]['ordersn']?>" readonly="readonly"/>
		</td>
	</tr>
	<tr >
		<td>创建时间：</td>
		<td class="select">
			<input type="text" value="<?=$this->cdate?>" class="cdate" readonly="readonly"/>
		</td>
		<td>佣金：</td>
		<td class="select">
			<input type="text" value="<?=sprintf("%.2f",$this->list[0]['amount'])?>" readonly="readonly"/>
		</td>
		<td class="select" colspan="2">
			<input type="button" class="btn btn-success" value="确认出库"/>
			<input type="button" class="btn btn-failed" value="取消"/>
		</td>
	</tr>
</table>

<div class="clear_fix"></div>
<br />
<div class="mj_list">
	<div class="table_title clearfix">
			<div class="title_left"><?=$this->module?></div>
			
		</div> 
		<div class="rk_table">
			<table class="data_table" border="0" cellpadding="0" cellspacing="0">
				<thead>
				<tr>
					<th >商品名称</th>
					<th >sku码</th>
					<th >采购价</th>
					<th >数量</th>
					<th >小计</th>
				</tr>
				</thead>
				<tbody>
			<?php 
				foreach ($this->list as $k=>$v){?>
					
				<tr>
					<td><?=$v['pname']?></td>
					<td><?=$v['suk']?></td>
					<td><?=sprintf("%.2f",$v['price'])?></td>
					<td><?=$v['counts']?></td>
					<td><?=sprintf("%.2f",$v['plus'])?></td>
				</tr>
				<?php }
			?>
				</tbody>
			</table>

		</div>
		<hr />
		<div class="show_input_btn">
			<input type="hidden" name="oid" class="oid" value="<?=$this->oid?>"/>
		</div>

</div>
<script>


	$('#load_data a').click(function(){

		rightATagClickListener($(this),'');
		return false;
	});
	//返回
	$('.btn-failed').click(function(){
		loadRightData('/stock/stockout','GET','');
	});
	//出库
	$('.btn-success').click(function(){		
		data = '';
		for (var i = 0; i < $('.inputsuk').size(); i++) {
			inputsuk = $('.inputsuk').eq(i);
			if(inputsuk.attr('value') == '' || inputsuk.attr('value') == ' '){
				jinggao("请输入suk码");
				$this = $(this);
				$(".jinggaobtn").click(function(){
					$(".jinggaoout").remove();	
					inputsuk.focus();
				});
				return;
			}
		}
		data += 'oid='+$('input.oid').attr('value');
		data += '&type='+<?=$this->type?>;
		data += '&stock_on='+$('input.stock_on').attr('value');
		data += '&cdate='+$('input.cdate').attr('value');


		result = ajaxPost(data,'/stock/stockout/output');
		if(result.stat){
			jinggao(result.message);
			$this = $(this);
			$(".jinggaobtn").click(function(){
				$(".jinggaoout").remove();	
				loadRightData('/stock/stockout','GET','');
			});
		}else{
			jinggao(result.message);
			$this = $(this);
			$(".jinggaobtn").click(function(){
				$(".jinggaoout").remove();	
			});
		}
		

	});


	//隔行变色
	$(".data_table tbody tr:odd td").css("background","#cbefde");
</script>