<?=$this->location?>

<div class="mj_list">
	<div class="table_title clearfix">
			<div class="title_left"><?=$this->module?></div>
			<div class="jrsc_fy" >
				<ul class="pagination">
					<?php 
						if ($this->PageList['left']) {?>
					<li><a href="<?=$this->url?>/search/expend?pageNum=1">&laquo;</a></li>
						<?php }
						if ($this->PageList['leftdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						foreach ($this->PageList['list'] as $v){
							$class=($v == $this->currentPage)?"class='active'":"";
					?>
					<li <?=$class?>><a href="<?=$this->url?>/search/expend?pageNum=<?=$v?>"><?=$v?></a></li>
						<?php }
					if ($this->PageList['rightdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						if ($this->PageList['right']) {?>
					<li><a href="<?=$this->url?>/search/expend?pageNum=<?=$this->totalPage?>">&raquo;</a></li>
						<?php }
					?>
				</ul>
			</div>
		</div> 
		<div class="rk_table">
			<table class="data_table" border="0" cellpadding="0" cellspacing="0">
				<thead>
				<tr>
					<th >编号</th>
					<th >交易方式</th>
					<th >支出卡号</th>
					<th >客户名称</th>
					<th >金额</th>
					<th >交易时间</th>
					<th >备注</th>
				</tr>
				</thead>
				<tbody>
			<?php 
				foreach ($this->list as $k=>$v){?>
					
				<tr>
					<td><?=($k+$this->offset+1)?></td>
					<td><?=$v['ctype']?></td>
					<td><?=$v['incomecard']?></td>
					<td><?=$v['membername']?></td>
					<td><?=sprintf("%.2f", $v['amount'])?></td>
					<td><?=$v['cdate']?></td>
					<td style="width:110px;"><?=$v['txt']?></td>
				</tr>
				<?php }
			?>
				</tbody>
			</table>

		</div>
		<hr />
		
		
	<div>
		<label>支出总额：</label>
		<input type="text" readonly="readonly" value="<?=sprintf("%.2f",$this->allcount)?>"/>
	</div>
				
				
</div>
<script>
	
	$('.query').click(function(){
		
		});

	$('#load_data a').click(function(){

		rightATagClickListener($(this),'');
		return false;
		});

	//隔行变色
	$(".data_table tbody tr:odd td").css("background","#cbefde");

</script>