<?=$this->location?>
<table class="cx_select">
	<tr>
		<td>订单编号：</td>
		<td class="select">
		
			<?php 
			//print_r($this->list);
			?>
			<input type="text" value="<?=$this->list[0]['ordersn']?>" readonly="readonly"/>
		</td>
		<td>创建时间：</td>
		<td class="select">
			<input type="text" value="<?=$this->list[0]['cdate']?>" readonly="readonly"/>
		</td>
		<td>订单状态：</td>
		<td class="select">
			<input type="text" value="<?=$this->list[0]['ostat']?>" readonly="readonly"/>
		</td>
		</tr>
		<tr>
		<td>佣金：</td>
		<td class="select">
			<input type="text" value="<?=$this->list[0]['amount']?>" readonly="readonly"/>
		</td>
		<td>总价：</td>
		<td class="select">
			<input type="text" value="<?=sprintf("%.2f",$this->list[0]['aamount'])?>" readonly="readonly"/>
		</td>
		<td class="select">
		<?php 
			if($this->list[0]['pstat']==0 && $this->list[0]['cstat'] == 0){?>
				
				<input type="button" id="acceptorder" class="btn btn-success" value="接受"/>
			<?php }
		?>
			<input type="button" style="margin-left:10px;" class="btn btn-failed" value="返回"/>
		</td>
	</tr>
</table>

<div class="clear_fix"></div>
<br />
<div class="mj_list">
<div class="table_title clearfix">
			<div class="title_left"><?=$this->module?></div>
			<div class="jrsc_fy" >
				<ul class="pagination">
					<?php 
						if ($this->PageList['left']) {?>
					<li><a href="<?=$this->url?>/order/myorder/info?id=<?=$this->list[0]['id']?>&pageNum=1">&laquo;</a></li>
						<?php }
						if ($this->PageList['leftdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						foreach ($this->PageList['list'] as $v){
							$class=($v == $this->currentPage)?"class='active'":"";
					?>
					<li <?=$class?>><a href="<?=$this->url?>/order/myorder/info?id=<?=$this->list[0]['id']?>&pageNum=<?=$v?>"><?=$v?></a></li>
						<?php }
					if ($this->PageList['rightdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						if ($this->PageList['right']) {?>
					<li><a href="<?=$this->url?>/order/myorder/info?id=<?=$this->list[0]['id']?>&pageNum=<?=$this->totalPage?>">&raquo;</a></li>
						<?php }
					?>
				</ul>
			</div>
		</div> 
		<div class="rk_table">
			<table class="data_table" border="0" cellpadding="0" cellspacing="0">
				<thead>
				<tr>
					<th ><span style="background-color: #17d2fa;"></span>商品名称</th>
					<th ><span style="background-color: #17fa61;"></span>采购价</th>
					<th ><span style="background-color: #e9bb2e;"></span>数量</th>
					<th ><span style="background-color: #be08ce;"></span>单位</th>
					<th ><span style="background-color: #fa6c17;"></span>小计</th>
				</tr>
				</thead>
				<tbody>
			<?php 
				foreach ($this->list as $k=>$v){?>
					
				<tr>
					<td><?=$v['pname']?></td>
					<td><?=sprintf("%.2f",$v['price'])?></td>
					<td><?=$v['counts']?></td>
					<td><?=$v['unit']?></td>
					<td><?=sprintf("%.2f",$v['plus'])?></td>
				</tr>
				<?php }
			?>
				</tbody>
			</table>

		</div>
		<hr />

</div>
<script>
	

	$('#load_data a').click(function(){

		rightATagClickListener($(this),'');
		return false;
	});
	//返回
	$('.btn-failed').click(function(){
		loadRightData('/order/myorder','GET','');
	});
	//购买
	$('.btn-success').click(function(){
		data= new Object();
		data.oid=<?=$this->list[0]['id']?>;
		resulta = ajaxPost(data,'/order/myorder/enoughmoney');
		if(resulta.stat){
			//显示输入密码款

			html = ajaxKeyboard('/order/myorder/keyboard?oid=<?=$this->list[0]['id']?> ');
			$('#load_data').append(html);
		}else{
			//显示余额不足
			
			jinggao(result.message);
			$this = $(this);
			$(".jinggaobtn").click(function(){
				$(".jinggaoout").remove();	
			});
		}
	});

	//隔行变色
	$(".data_table tbody tr:odd td").css("background","#cbefde");

</script>