<?=$this->location?>

<div class="mj_list">
	<div class="mj_list_content">
		<div class="table_title clearfix">
			<div class="title_left"><?=$this->module?></div>
			<div class="jrsc_fy" >
				<ul class="pagination">
					<?php 
						if ($this->PageList['left']) {?>
					<li><a href="<?=$this->url?>/search/index?pageNum=1">&laquo;</a></li>
						<?php }
						if ($this->PageList['leftdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						foreach ($this->PageList['list'] as $v){
							$class=($v == $this->currentPage)?"class='active'":"";
					?>
					<li <?=$class?>><a href="<?=$this->url?>/search/index?pageNum=<?=$v?>"><?=$v?></a></li>
						<?php }
					if ($this->PageList['rightdot']) {?>
							
					<li><a class="dot" href="">...</a></li>
						<?php }
						if ($this->PageList['right']) {?>
					<li><a href="<?=$this->url?>/search/index?pageNum=<?=$this->totalPage?>">&raquo;</a></li>
						<?php }
					?>
				</ul>
			</div>
		</div> 
		<div class="rk_table">
			<table class="data_table" border="0" cellpadding="0" cellspacing="0">
				<thead>
				<tr>
					<th >编号</th>
					<th >交易方式</th>
					<th >对方卡号</th>
					<th >客户名称</th>
					<th >金额</th>
					<th >交易时间</th>
					<th >备注</th>
				</tr>
				</thead>
				<tbody>
			<?php 
				foreach ($this->list as $k=>$v){?>
					
				<tr>
					<td><?=($k+$this->offset+1)?></td>
					<td><?=$v['ctype']?></td>
					<td><?=$v['paycard']?></td>
					<td><?=$v['membername']?></td>
					<td><?=sprintf("%.2f", $v['amount'])?></td>
					<td><?=$v['cdate']?></td>
					<td><?=$v['txt']?></td>
				</tr>
				<?php }
			?>
				</tbody>
			</table>

		</div>		
		<hr />
	<div class="clearfix"></div>
	
	<?php
	
		$classleft = ($this->currentPage == 1)?"slidehide":"";
		$classright = ($this->currentPage == $this->totalPage)?"slidehide":"";		
		if($this->totalPage <=1){
			$classleft='';
			$classright='';
		}
	?>
	<div class="slide slideleft <?=$classleft?>"><a href="<?=$this->url?>/search/index?pageNum=<?=($this->currentPage-1)?>">&nbsp;</a></div>
	<div class="slide slideright <?=$classright?>"><a href="<?=$this->url?>/search/index?pageNum=<?=($this->currentPage+1)?>">&nbsp;</a></div>		
</div>
<script>
	
	$('.query').click(function(){
		
		});

	$('#load_data a').click(function(){

		rightATagClickListener($(this),'');
		return false;
		});
	//隔行变色
	$(".data_table tbody tr:odd td").css("background","#cbefde");
	
	//翻页
	slidesome();


</script>